In [3]:
import pandas as pd

# 1. Load the data
# Use 'engine="pyarrow"' to ensure it uses the library we installed
df = pd.read_parquet('data/parquet/products.parquet', engine='pyarrow')

# 2. Basic Exploration
print(f"Dataset Shape: {df.shape}")
display(df.info())    # Shows column types and memory usage
display(df.head())    # Shows the first 5 rows in a clean table

Dataset Shape: (40341, 6)
<class 'pandas.DataFrame'>
RangeIndex: 40341 entries, 0 to 40340
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     40341 non-null  str
 1   title          40341 non-null  str
 2   brand          40341 non-null  str
 3   price          40341 non-null  str
 4   category_path  40341 non-null  object
 5   description    40341 non-null  object
dtypes: object(2), str(4)
memory usage: 7.4+ MB

None

,product_id,title,brand,price,category_path,description
0,B004E2Z88O,Motorola Droid X Essentials Combo Pack,Verizon,14.99,"[Electronics, Computers & Accessories, Compute...",[all Genuine High Quality Motorola Made Access...
1,B07BJ7ZZL7,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...",QGHXO,14.89,"[Electronics, Wearable Technology, Arm & Wrist...","[Compatibility, Custom designed for your preci..."
2,B00R6R82HS,"Fishfinder, Depth Finder Poly Sun Cover for 3""...",Westlake Market,10.99,"[Electronics, Car & Vehicle Electronics, Marin...",[Affordable and convenient way to cover your s...
3,B07Y6K1PRB,Novelty Cute Cartoon USB 2.0 Flash Drive Data ...,Fire Stone,8.98,"[Electronics, Computers & Accessories, Data St...",[This is a special usb stick that make as a cu...
4,B07848ZT9T,ANNKE 4K 16CH Security DVR Recorder with Human...,ANNKE,909.99,"[Electronics, Security & Surveillance, Surveil...",[ANNKE 16 channel 4K DVR security camera syste...

In [4]:
# 1. Load the data
# Use 'engine="pyarrow"' to ensure it uses the library we installed
df2 = pd.read_parquet('data/parquet/transactions.parquet', engine='pyarrow')

# 2. Basic Exploration
print(f"Dataset Shape: {df2.shape}")
display(df2.info())    # Shows column types and memory usage
display(df2.head())    # Shows the first 5 rows in a clean table

Dataset Shape: (80000, 4)
<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    80000 non-null  str
 1   user_id     80000 non-null  str
 2   product_id  80000 non-null  str
 3   timestamp   80000 non-null  str
dtypes: str(4)
memory usage: 6.6 MB

None

    order_id           user_id  product_id            timestamp
0  ORD_05001  USR_FB1952A9C606  B08137DPFK  2026-08-25 19:39:52
1  ORD_05002  USR_21F6CC41124D  B00A2VBOFM  2026-07-20 14:20:47
2  ORD_05002  USR_21F6CC41124D  B081CMSZ45  2026-07-20 14:20:47
3  ORD_05002  USR_21F6CC41124D  B07NVRWN9M  2026-07-20 14:20:47
4  ORD_05002  USR_21F6CC41124D  B0BMWJ414V  2026-07-20 14:20:47